# Generated by Django 3.1.1 on 2020-09-14 03:04

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', phone_field.models.PhoneField(max_length=31)),
                ('street_name', models.CharField(max_length=120)),
                ('number', models.SmallIntegerField(blank=True, default=0)),
                ('compliment', models.CharField(blank=True, max_length=100)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('zipcode', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
