# Generated by Django 3.1.1 on 2020-09-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
