# Generated by Django 3.1.1 on 2020-09-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_date_of_last_buy'),
        ('sale', '0003_remove_sale_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(related_name='sale_products', to='product.Product'),
        ),
    ]
