# Generated by Django 3.1.1 on 2020-09-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_auto_20200921_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='product',
            new_name='products',
        ),
    ]
